name: Publish NPM Package

on:
  workflow_dispatch:

jobs:
  # Before being ran, this workflow assumes that the package version in package.json has been manually bumped to a new version with `npm install` being run to update package-lock.json as well.
  # The publication of the package will fail if the version in package.json is not updated.
  publish-npm-package-to-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    name: Publish NPM Package
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Publish Package
        run: npm publish
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}